### ISSUE TITLE
colab crash/stop randomly

### ISSUE THREAD

**Issue by vibicer** [cagliostrolab/forge-colab#3]
![image](https://github.com/user-attachments/assets/1faccfc1-52fa-4461-b6d2-3b5370eb8de0)
For example, when upscaling, loading models, or performing any other task, the Colab suddenly crashes or stops.

I only downloaded 1-2 models around 2gb/6gb sizes, 2 loras. thats it. SD/SDXL

The generate settings 512x768 upscale 2x.

**Comment by Varkilister** [comment]
don't use upscaler

**Comment by vibicer** [comment]
> don't use upscaler

it's crashed when loading models or any other activities, randomly.

**Comment by Linaqruf** [comment]
Avoid using the upscaler if you are a free-tier Colab user. In Forge, the models load once you press generate, so the possibility of a crash is high.
