### ISSUE TITLE
Are LORAs broken? 

### ISSUE THREAD

**Issue by Ayaya70** [cagliostrolab/forge-colab#6]
I've been trying this all afternoon, goddamnit. I opened Colab today after a week, and suddenly none of the LORAs I try work. I always set it up manually—I'd open the webui-colab folder, go to models, and upload everything to the LORA folder. But literally none of them are working now. Could anyone help me out somehow?
I also tried uploading all the LORAs to HuggingFace and then adding them in the "custom_lora_url" tab that our Colab provides, but that didn't work either. I'm not sure what else I can try, tbh.

I'd also like to ask when the maintenance on the refiner will be finished. Sorry for all the questions, and thanks for reading.

**Comment by nawka12** [comment]
Sorry for the belated respond. Our maintainer is out of town, and most of our team have main jobs so it took a while to be able to respond.

LoRAs works fine for me.
![image](https://github.com/user-attachments/assets/093e00a3-f579-4eb7-9e92-6e47021605f0)

Can you give me more details on the issue you're having?

**Comment by Ayaya70** [comment]
Hello, don't worry, it's fine, thank you for replying! I probably did something wrong because that same day I managed to resolve it. It was a bad LORA, and I ended up getting paranoid thinking that the others weren’t working either. When I typed in the prompt to activate the LORA, the image didn’t match the character I wanted, basically
